services:
  django:
    build: .
    container_name: django_app
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./configs/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

networks:
  default:
    driver: bridge